#!/usr/bin/env bash
#ENV VARS
OS=$(uname)
OS_VERSION=$(uname -r)
UNAME_M=$(uname -m)
ARCH=$(uname -m)
AWK=$(which awk)
GAWK=$(which gawk)
export OS
export OS_VERSION
export UNAME_M
export ARCH
export AWK
export GAWK

if [[ ! -z "$GAWK" ]]; then
    AWK=$(which gawk)
    export AWK
    echo $AWK
fi

export PATH=$PATH:/usr/local/opt/python@${python_version_major}.${python_version_minor}/Frameworks/Python.framework/Versions/${python_version_major}.${python_version_minor}/bin

report() {
echo OS:
echo "$OS" | "$AWK" '{print tolower($0)}'
echo OS_VERSION:
echo "$OS_VERSION" | "$AWK" '{print tolower($0)}'
echo UNAME_M:
echo "$UNAME_M" | "$AWK" '{print tolower($0)}'
echo ARCH:
echo "$ARCH" | "$AWK" '{print tolower($0)}'
echo OSTYPE:
echo "$OSTYPE" | "$AWK" '{print tolower($0)}'
}

checkbrew() {

arch_name="$(uname -m)"

if [ "${arch_name}" = "x86_64" ]; then
    if [ "$(sysctl -in sysctl.proc_translated)" = "1" ]; then
        echo "Running on Rosetta 2"
    else
        echo "Running on native Intel"
    fi
elif [ "${arch_name}" = "arm64" ]; then
    echo "Running on arm64"
elif [ "${arch_name}" = "aarch64" ]; then
    echo "Running on aarch64"
else
    echo "Unknown architecture: ${arch_name}"
fi

if hash apt-get 2>/dev/null; then
    sudo apt-get update
    sudo apt-get install -y \
    python3 python3-pip \
	python-tk python3-tk
    if ! hash pip3 2>/dev/null; then
	sudo apt-get install python3-pip
    pip3 install PySimpleGUI
    else
        pip3 install PySimpleGUI
    fi
exit
fi

if hash brew 2>/dev/null; then
	brew install python-tk@${python_version_major}.${python_version_minor}
	brew install openssl@3
    if ! hash gawk 2>/dev/null; then
        brew install gawk
    fi
    brew install --quiet  --force python@3.9
	brew link python@3.9
	brew install python-tk@3.9
    if   hash pip3 2>/dev/null; then
		pip3 install PySimpleGUI
    else
		python3.9 -m pip install PySimpleGUI
    fi

	PYTHON3=$(command -v python3)
	$PYTHON3 -m pip -q install --upgrade pip || echo
    echo
else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    checkbrew
fi
}
checkraspi(){

    echo 'Checking Raspi'
    if [ -e /etc/rpi-issue ]; then
    echo "- Original Installation"
    cat /etc/rpi-issue
    fi
    if [ -e /usr/bin/lsb_release ]; then
    echo "- Current OS"
    lsb_release -irdc
    fi
    echo "- Kernel"
    uname -r
    echo "- Model"
    cat /proc/device-tree/model && echo
    echo "- hostname"
    hostname
    echo "- Firmware"
    /opt/vc/bin/vcgencmd version
}

if [[ "$OSTYPE" == "linux"* ]]; then
    #CHECK APT
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        if hash apt 2>/dev/null; then
            sudo apt install "$AWK"
            sudo apt update
            sudo apt install software-properties-common
            sudo apt install python3
            sudo apt-get install python3-pip
			sudo apt-get install build-essential libssl-dev libffi-dev \
    python3-dev cargo pkg-config
            report
            echo 'Using apt...'
        fi
    fi
    if [[ "$OSTYPE" == "linux-musl" ]]; then
        if hash apk 2>/dev/null; then
            apk add "$AWK"
            report
            echo 'Using apk...'
            apk add python3 py3-pip
            python3 -m pip install -r requirements.txt || \
            python3 -m pip install -r ../requirements.txt


        fi
    fi
    if [[ "$OSTYPE" == "linux-arm"* ]]; then
        checkraspi
        if hash apt 2>/dev/null; then
            apt install "$AWK"
            report
            echo 'Using apt...'

        fi
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    checkbrew
elif [[ "$OSTYPE" == "cygwin" ]]; then
    echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "msys" ]]; then
    echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "win32" ]]; then
    echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "freebsd"* ]]; then
    echo TODO add support for $OSTYPE
else
    echo TODO add support for $OSTYPE
fi

